### PR TITLE
Interoperate with host loader

### PR DESCRIPTION
**Pull request by heimir-sverrisson**
A series of small changes and additions to the flash loader to make interaction with the host loader easier.

### CODE REVIEW

**Review by burnsfisher — COMMENTED** [review]
Would be ideal if the actual memory size could be determined programmatically.

**Review by burnsfisher — COMMENTED** [review]
Is this gio the one that represents the "attached" pin on the s/c bus?  I.e. the one that says there is an umbilical plugged in?   The name "forced" makes me wonder if the right thing is happening here.  Typically, one might attach either the loader app OR a terminal.  For the loader, obviously we load a program.  But we also want to be able to plug in a terminal in order to boot the existing code, yet have access to the console serial line to issue test/debug commands.

**Review by burnsfisher — COMMENTED** [review]
I'm a little unclear about what is going on here.  I think that one wants to start the loader if any of the following is true:  1) There is no program there (your comment says this, but it can't be all that common), 2) The "attached" line is high, and 3) The program has NOT set a flag that says "don't stop in loader".  That is, the program should be able to reboot without entering the loader even if a terminal is connected and the attached line is high.  Is this anything like what is going on?

**Comment by heimir-sverrisson** [comment]
> Would be ideal if the actual memory size could be determined programmatically.

I agree. I will address that when I get my hands on a real rt-ihu, as the code will need small tweaks to accommodate that board.

**Comment by heimir-sverrisson** [comment]
> Is this gio the one that represents the "attached" pin on the s/c bus? I.e. the one that says there is an umbilical plugged in? The name "forced" makes me wonder if the right thing is happening here. Typically, one might attach either the loader app OR a terminal. For the loader, obviously we load a program. But we also want to be able to plug in a terminal in order to boot the existing code, yet have access to the console serial line to issue test/debug commands.

This is not the correct pin for the umbilical, but the change should be trivial when I get an actual rt-hiu to test and adapt this code to. Forced is a term coined by TI, basically forcing the flash loader to enter prompt mode rather than going on to run the application code. When a terminal is connected using the current code, it will stop with a single `$ ` prompt, and then when a user hits `3` the application will be available on the port for any commands/test/debug.

**Comment by burnsfisher** [comment]
Ok, that's great--sound perfect.  I should have said that this code is what
would be supporting the attached pin on the RTIHU.  Thanks.

**Comment by heimir-sverrisson** [comment]
> I'm a little unclear about what is going on here. I think that one wants to start the loader if any of the following is true: 1) There is no program there (your comment says this, but it can't be all that common), 2) The "attached" line is high, and 3) The program has NOT set a flag that says "don't stop in loader". That is, the program should be able to reboot without entering the loader even if a terminal is connected and the attached line is high. Is this anything like what is going on?

You are right about 1) and 2) but 3) is not at all implemented. With a terminal attached there is the minor inconvenience of having to hit the letter `3` to continue to the application code. If we want to implement 3) we would just have to agree on a variable at a certain offset in RAM, that can be set by the application code, and checked by the flash loader.

**Comment by burnsfisher** [comment]
Ok, thanks.  That feature is very convenient for debugging on the LIHU
(especially when gdb is connected to it--and you are right that it is easy
to implement.

**Pull request merged**
