### PR TITLE
First working version of the flash loader

### PR DESCRIPTION
**Pull request by heimir-sverrisson**
A lot of things still need to be cleaned up, including all kinds of prompts from the TI code that have no value when operated from a host loader program. This is very much work in progress still, but the highlights of the changes done to the code from TI are as follows:

* Remove code related to CAN and SPI versions of the boot loader and getting rid of `#ifdefs` related to that.
* Making the chatty prompts and messages disappear behind `#ifdef DEBUG_MSG`
* Cleaning up the `main()` function that had redundant code
* Added a new menu item to `bl_uart.c` and moving the menu itself into a separate function invoked by `?`
* Considerable clean up and bug fixes in the y-modem protocol in `bl_ymodem.c`, which was very flaky from TI
* No changes to any `hw_*.c` or `Fapi*.c` files.
* Clean up of function output in `sw_hw_ver.c` among other things replacing constant `CRLF` for `\r\n`.
* The rest is TI code formatted as standard K&R.

### CODE REVIEW

**Review by burnsfisher — COMMENTED** [review]
I'd like to see some comments about using TI Copyrighted code in other open source code. They say something about not allowing it in "Viral" code, but I don't know what that means. Comments anyone?
(Not my full review.  Will look at more code later)

**Comment by heimir-sverrisson** [comment]
> I'd like to see some comments about using TI Copyrighted code in other open source code. They say something about not allowing it in "Viral" code, but I don't know what that means. Comments anyone? (Not my full review. Will look at more code later)

I agree, I don't know what they mean. It would be great if we can decide on a Copyright clause for this code coming from TI and modified by us.

**Comment by burnsfisher** [comment]
Just to be clear--yes, we probably need to add some code comments--as you say a standardized  thing of some sort.  However, I really meant we need to talk it around ourselves.  Maybe Jonathan has some thoughts.

**Comment by jonathanbrandenburg** [comment]
> They say something about not allowing it in "Viral" code, but I don't know what that means.

Some licenses, like GPL are considered "viral". There are circumstances where the use of GPL licensed code requires you to release your modifications under the GPL license, hence the license propagates to your code. (To be clear, some folks will disagree with the use of the term "viral" because you would be voluntarily using software with a GPL license and not inadvertently infecting your code with GPL.)

Other licenses, such as MIT are much more permissive. I use MIT for my AMSAT open source repositories.

**Comment by jonathanbrandenburg** [comment]
> I'd like to see some comments about using TI Copyrighted code in other open source code.

If you can point me to the TI license for their code, I'm happy to look at it. (I just haven't tracked it down yet.)

**Comment by burnsfisher** [comment]
An example is at the top of this code:
https://github.com/AMSAT-NA/flash-boot-loader-ti/blob/hs/initial_code/src/bl_check.c

**Comment by burnsfisher** [comment]
Wow!  I'm having a very hard time with this.   Partly because I'm not accustomed to the git review infrastructure.  But also (probably partly the same thing) that it was hard to tell what you (Heimir) have done vs what was there from TI.  (I don't really want to review what TI did except as I need to understand it to review the changes).  

So maybe best to ask a few questions, which I hope are not things that draw sighs.  They may also be related to knowing more about how the ST version works while I have used a lot of the TI HAL code in the flight software so I'm less comfortable knowing how the TMS570 works down at the bottom level.  Anyway:

1) Which modules are actually used to write into flash memory?  Do you have to copy the loader into sram and execute it there in order to write to flash?  (That was the case with ST).  This is mostly curiousity, and just trying to straighten out in my head how this works.

2) There is a comment about initializing the vectors for the loader to use.  How do they get changed to vector handlers in the application code that is loaded?  (In ST there is a register into which you write the base address of the vectors, so the application must have non-default code there in order to have the application vectors above the flash loader)

3) Do you have a plan for how the flash loader gets loaded?  Is it fair to assume that you do it with the standard XDS110 (or equiv) hardware and s/w?

4) Once the flash loader is installed, can the application be loaded and debugged with the XDS110 or must it then always be loaded via the flash loader (with no debugging possible)? 

5) Have you already added the capability to only start the flash loader when the "attached" line is high?  I saw some code that seemed to behave differently based on a particular GPIO, but there were no obvious comments about what that was all about.

6) I'd really like to see more "how this works" comments.  Maybe it starts by a few more details in the MD file while code comments referring to it something like "this is how we accomplish xxx as shown in the MD file".  I know there are different opinions about commenting; if I am in the distant minority here, we should at least talk about how I can better understand the code.

**Comment by heimir-sverrisson** [comment]
> Wow! I'm having a very hard time with this. Partly because I'm not accustomed to the git review infrastructure. But also (probably partly the same thing) that it was hard to tell what you (Heimir) have done vs what was there from TI. (I don't really want to review what TI did except as I need to understand it to review the changes).
Yes, as a rule I would not push up such a whopper of a PR, but most of it is TI code that I've had to adapt. I've updated the PR description to enumerate my modifications to the TI code (as I should have done in the first place).

> 
> So maybe best to ask a few questions, which I hope are not things that draw sighs. They may also be related to knowing more about how the ST version works while I have used a lot of the TI HAL code in the flight software so I'm less comfortable knowing how the TMS570 works down at the bottom level. Anyway:
> 
> 1. Which modules are actually used to write into flash memory?  Do you have to copy the loader into sram and execute it there in order to write to flash?  (That was the case with ST).  This is mostly curiousity, and just trying to straighten out in my head how this works.
Yes, TMS570 has to copy the Flash Programming code to RAM before loading the application. This is done with a TI library (FAPI).

> 2. There is a comment about initializing the vectors for the loader to use.  How do they get changed to vector handlers in the application code that is loaded?  (In ST there is a register into which you write the base address of the vectors, so the application must have non-default code there in order to have the application vectors above the flash loader)
TMS570 has the same offset register for interrupt vectors as STM. When the application is linked with an offset from 0x0 as start address, this code is run by HalCodeGen generated code before the call to `main()`. See a separate comment on it, that I will put into the `README.md` file, once I've tried all this better end-to-end.
 
> 3. Do you have a plan for how the flash loader gets loaded?  Is it fair to assume that you do it with the standard XDS110 (or equiv) hardware and s/w?
I've been using the standard XDS110 method to load the flash loader into the first 64k of flash (application offset 0x0).

> 4. Once the flash loader is installed, can the application be loaded and debugged with the XDS110 or must it then always be loaded via the flash loader (with no debugging possible)?
Once the flash loader is installed the application can be loaded and debugged with the XDS110, when properly built with memory offset of 0x10100. This calls for a simple one time modification of the `*.cmd` link control file. Care must be taken to not wipe out the first 64k of flash when deploying from CCS, but that is also a simple one off setting.
 
> 5. Have you already added the capability to only start the flash loader when the "attached" line is high?  I saw some code that seemed to behave differently based on a particular GPIO, but there were no obvious comments about what that was all about.
The TI code already had that functionality, except it looks for a `low` value, which I have not updated yet. But I've tested this functionality on the Dev Kit and it works as expected. Once I've flashed an application, either a simple bare bones, or FreeRTOS the flash loader will start the application after power on reset every time, except if the GPIO pin is active, when it will present a prompt and allow for another application to be flashed.

> 6. I'd really like to see more "how this works" comments.  Maybe it starts by a few more details in the MD file while code comments referring to it something like "this is how we accomplish xxx as shown in the MD file".  I know there are different opinions about commenting; if I am in the distant minority here, we should at least talk about how I can better understand the code.
This is very much work in progress, hence the word 'First' in the name of PR :-) I just wanted to get this in front of people at the earliest moment possible. I certainly will add much more meat to the `README.md` file explaining all the things I wrote above and more.

**Comment by heimir-sverrisson** [comment]
A typical simple application will have a `MEMORY` section in the linker file looking like: 
```
    VECTORS (X)  : origin=0x00000000 length=0x00000020
    FLASH0  (RX) : origin=0x00000020 length=0x0013FFE0
    STACKS  (RW) : origin=0x08000000 length=0x00001500
    RAM     (RW) : origin=0x08001500 length=0x0002EB00
```
When used with this flash loader the flash addresses are translated up by `0x10100` bytes to look like:
```
    VECTORS (X)  : origin=0x00010100 length=0x00000020
    FLASH0  (RX) : origin=0x00010120 length=0x0012FEE0
    STACKS  (RW) : origin=0x08000000 length=0x00001500
    RAM     (RW) : origin=0x08001500 length=0x0002EB00
```
Note that the length of the `FLASH0` has to be shortened by the new offset too.
(This text will be added to the `README.md` file too).

**Comment by jonathanbrandenburg** [comment]
Got it! Will review Sent from Proton Mail for iOS On Sun, Aug 28, 2022 at 2:17 PM, Heimir Sverrisson ***@***.***> wrote:  
@heimir-sverrisson requested your review on: #1 First working version of the flash loader.

**Pull request merged**
